# Generated by Django 3.2.9 on 2021-12-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20200507_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
